logs:
  - name: stderr
    level: info
    output:
      kind: file
      file: /dev/stderr

models:
  - name: model1
    api:
      kind: openai
      url: http://localhost:9652

lsps:
  - name: clangd
    api:
      kind: stdio
      cmd:
        - clangd

handlers:
  - name: completion
    kind: lsp/completion
    resources:
      - name: model1
        model: model1
        scope: client
      - name: clangd
        lsp: clangd
        scope: client
    endpoints:
      textDocument/completion:
        default: false
        execution:
          - lsp/completion:
              resource: clangd
            assign: clangd

          - model:
              resource: model1
              parameters:
                schema: json/completionItem
                max_tokens: 512
                temperature: 0.2
              messages:
                - role: system
                  content: "You are a code completion engine. The user message contains source code with exactly one <CURSOR> marker. Return only the text that should replace <CURSOR>. Do not return the code before <CURSOR>. Do not return the code after <CURSOR>. Do not return <CURSOR>. Do not use Markdown. Do not use code fences. Do not start with ```. Your response will be inserted directly into the file, so every character you output must be valid source-code text for that insertion point. Use received LSP-server textDocument/completion details to generate better completion result."
                - role: user
                  content: |
                    LSP textDocument/completion results: [{{- range $i, $item := .clangd }}{{- if $i }},{{ end }}{{ printf "%q" $item.Label }} {{- end }}]
                - role: user
                  content: |
                    {{ .file.text_before }}<CURSOR>{{ .file.text_after }}
            assign: llm_result

          - json/parse/completion:
              input: "[{{ .llm_result }}]"
            assign: completion_json

          - return: "{{ .completion_json }}"

listeners:
  - name: api-tcp:9650
    ipc:
      kind: tcp
      port: 9650
    protocol:
      kind: api
  - name: lsp-tcp:9651
    ipc:
      kind: tcp
      port: 9651
    protocol:
      kind: lsp
      handlers:
        - name: completion
          condition:
            filetypes: null
            path: null
          handler: completion
